### ISSUE TITLE
[Profiler] Feature request: scroll/jump in event list

### ISSUE THREAD

**Issue by fmalcher** [mgechev/eap-feedback#1]
When toggling through the event list, you can only take one step at a time. When the list is long (hundreds long) it's painful to get to the start or end.

Ideas:
- Make the list scrollable
- Add paging
- Add "jump to start/end" buttons

![Screenshot 2021-03-19 at 10 08 40](https://user-images.githubusercontent.com/1683147/111757544-bac96000-889b-11eb-8b88-e833f0eb5eaf.png)

**Comment by mgechev** [comment]
>Make the list scrollable

On what operating system are you using DevTools? It should have `overflow-y` set to scroll.

We'll also add filtering in the final release which should make things easier.

**Comment by twerske** [comment]
Paging is a good idea - would you want sort options on the list in addition to filtering?

**Comment by mgechev** [comment]
@fmalcher did you have a chance to try the new filtering? Does this help with the issue?

**Comment by fmalcher** [comment]
> @fmalcher did you have a chance to try the new filtering? Does this help with the issue?

Thanks for the reminder and for the implementation! 🙂 Yes and no:

- Can you put the filtering description somewhere else than in the placeholder? It's not fully displayed for me (inspected it to read the full text)
- In order to remove certain event sources, something like `source: !message` would come in handy

**Comment by mgechev** [comment]
Just increased the width. Having `!source: message` sounds like a nice feature that we can prioritize before the release :)

**Comment by mgechev** [comment]
We have `!source: message` in the latest release (give it a try).

We're also about to publish drag to scroll. Closing this issue.
