### ISSUE TITLE
Element select icon misleading

### ISSUE THREAD

**Issue by fmalcher** [mgechev/eap-feedback#10]
Me again with an icon issue 😅
I highly misinterpreted the "Select element" button at the very top left of the DevTools. For me, the icon suggests "undock into separate window". Can we find an icon more similar to Chrome's select icon?

![Screenshot 2021-05-06 at 09 18 23](https://user-images.githubusercontent.com/1683147/117257675-734b6300-ae4c-11eb-9b26-03e4ae75edc8.png)

**Comment by tieppt** [comment]
The first time using the dev tools, I thought the button serves the same purpose. =)))

**Comment by mgechev** [comment]
We added tooltips which should make it more obvious. We're using Material Icons so that's the best we could do unless we want to switch to a custom image :). Let's close for now and see what people think.
