### ISSUE TITLE
Feature: Tooltips for icon buttons

### ISSUE THREAD

**Issue by fmalcher** [mgechev/eap-feedback#11]
Request: Add tooltips/titles for icon buttons so that users can understand the purpose without trying things out.
Particulary applies to those:

- Select element (top left)
- Open component source (top right)
- Open docs reference (for Inputs/Outputs of a Component)
- Up/down buttons in the search bar

**Comment by mgechev** [comment]
Fixed by https://github.com/rangle/angular-devtools/pull/754.
