### ISSUE TITLE
[Feature Request] Auto expand the component tree when the developer select a component

### ISSUE THREAD

**Issue by tieppt** [mgechev/eap-feedback#13]
Prerequisite: The developer has collapsed the component tree.
![image](https://user-images.githubusercontent.com/7151365/117482838-26bc7080-af8f-11eb-9d6e-8d62ff727178.png)

As a developer, I want to expand the collapsed component tree when I select a component using the selector function.
![image](https://user-images.githubusercontent.com/7151365/117483041-6aaf7580-af8f-11eb-8c27-f9eaef37641c.png)

**Comment by mgechev** [comment]
Fixed by https://github.com/rangle/angular-devtools/pull/756.
