### ISSUE TITLE
Chrome Plugin

### ISSUE THREAD

**Issue by fkolar** [mgechev/eap-feedback#4]
I have tried this new Chrome plugin on one of our demo app, and I found, it probably does not work with Dynamic Components ? 

I have this page, which is instantiated dynamically, but the Angular Console shows just first root tag. 
Are there any restrictions? 

<img width="1614" alt="Screen Shot 2021-03-24 at 8 31 16 AM" src="https://user-images.githubusercontent.com/17149942/112271541-5895a400-8c7b-11eb-93f6-39de8084b0f9.png">

**Comment by Splaktar** [comment]
It might be helpful if you could share some of the related template or a screenshot of the DOM tree for comparison.

**Comment by fkolar** [comment]
Attaching screenshots both from app template where everything is started, plus DOM structure. Its based on Rule Driven UI. 

https://www.metaui.io
https://docs.metaui.io/fundamentals/rules


<img width="1241" alt="Screen Shot 2021-03-24 at 9 17 14 AM" src="https://user-images.githubusercontent.com/17149942/112277362-f8563080-8c81-11eb-8786-63ee0efd472a.png">

<img width="830" alt="Screen Shot 2021-03-24 at 9 19 21 AM" src="https://user-images.githubusercontent.com/17149942/112277432-073ce300-8c82-11eb-91dc-53f8d0964dad.png">

**Comment by mgechev** [comment]
Thanks for the report! This is a known issue we should resolve for v12 once we improve the DevTools-framework integration.

**Comment by mgechev** [comment]
@fkolar could you give this a try with Angular v12? The latest prerelease includes a new set of APIs which resolve the issue.

Let me know what you find!

**Comment by fkolar** [comment]
@mgechev cool. I will. Does my lib needs to be upgraded to v12 before trying this out? Or just enough for the app to be on v12?

**Comment by mgechev** [comment]
Should be enough for the app to be on v12.

**Comment by mgechev** [comment]
@fkolar any updates?

**Comment by fkolar** [comment]
Thanks for reminding me.. I was about to test it this weekend

**Comment by fkolar** [comment]
Now it works and I can see structure. but I am not sure I should see some state on the right side (Properties as all is empty)

<img width="1584" alt="Screen Shot 2021-05-01 at 8 44 44 AM" src="https://user-images.githubusercontent.com/17149942/116774007-a1e6c980-aa59-11eb-9a5c-ed8d368210ab.png">


You can check it out under:  https://github.com/fkolar/ng-debug-tool

where this is the page which renders UI (using our rule engine):
https://github.com/fkolar/ng-debug-tool/blob/master/src/app/user-detail/user-detail.component.html
Based on object stylesheet: https://github.com/fkolar/ng-debug-tool/blob/master/src/app/rules/User.oss

npm install

ng serve

**Comment by mgechev** [comment]
>Now it works and I can see structure. but I am not sure I should see some state on the right side (Properties as all is empty)

Not sure I understand. Are there missing properties?

**Comment by fkolar** [comment]
Yes properties on the right, are empty, You click on the` {....},` and there is nothing.

**Comment by mgechev** [comment]
I can't reproduce this problem:

<img width="1810" alt="Screen Shot 2021-05-03 at 10 16 37 AM" src="https://user-images.githubusercontent.com/455023/116909168-ac8b9500-abf8-11eb-9a19-6e6e411a1c49.png">

Just cloned the repo, ran:

```
npm i
yarn watch:oss
ng serve
```

Opened DevTools 1.0.21 and everything just worked. Anything I'm missing?

**Comment by fkolar** [comment]
When I look at your picture all seems correct., when I click on {..} I had no content in there. I will have to double check. What chrome version are you using ?

**Comment by fkolar** [comment]
It seem most of the properties are initialized but there are some which are empty. 
<img width="1568" alt="Screen Shot 2021-05-03 at 10 52 02 PM" src="https://user-images.githubusercontent.com/17149942/116932380-784cbe80-ac62-11eb-8053-6db4b29252e2.png">



In this case of `_binidngsMap` I do initialize this during a ngInit. 
https://github.com/ngx-metaui/rules/blob/0ce93b95d2e009da942632ca3299f71700e4ca54/libs/rules/src/lib/metaui/core/meta-context/meta-context.component.ts#L204
