### ISSUE TITLE
[Feature Request] Router Tree

### ISSUE THREAD

**Issue by web-dave** [mgechev/eap-feedback#5]
I would love to be able to inspect the Router Tree of my app.
I would love to see:
* Graphical representation of the Routertree
* RouterState
* Guards

This could become very handy.

(I know there was such a feature in Augury.)

**Comment by tieppt** [comment]
I think this tab is hidden right now (I saw it when I inspect the source code of the dev tools)

**Comment by mgechev** [comment]
Thanks for the request!

Yes, we have a prototype and the tab is currently hidden.

Since this is on the roadmap, I'll close the issue for now.
