### ISSUE TITLE
Angular application not detected with Electron

### ISSUE THREAD

**Issue by bampakoa** [mgechev/eap-feedback#6]
I get the message **Angular application not detected** when using it in an Angular application that is rendered inside an Electron window. Below are some details about my case:

1. The Electron window loads the main **index.html** file of the Angular application using `file://` protocol.
2. The Angular application has been built with `ng build`
3. I have unpacked the extension inside the `assets` folder and I am loading it inside Electron using the following snippet  `session.defaultSession.loadExtension(__dirname + '/assets/hhbbfggmgbhhpokkkiofojiicllfngkf');` .
4. I have followed [this](https://www.electronjs.org/docs/api/extensions#chrome-extension-support) guide from the Electron official documentation to load the extension.

![image](https://user-images.githubusercontent.com/7170892/112306095-19317c80-8ca8-11eb-9d3b-b2ce1c8e7b34.png)

Thanks!

_**Notice: The extension is loaded correctly when I use the `loadURL` method of Electron to load the Angular application directly from http://localhost:4200**_

**Comment by mgechev** [comment]
Thanks for the report! That's not a use case we support.

When we share the project we can consider implementing this feature request based on the community feedback given the focus of the project.
