### ISSUE TITLE
[Router Tree] Feature: Add the possibility to Save it

### ISSUE THREAD

**Issue by lamisChebbi** [mgechev/eap-feedback#8]
Hi, 

I used the Angular Dev Tools for a big application, when you move to the Router Tree tab you can't visualize the tree properly (because of the number of components)
It would be a good idea if we can save the tree to another format. I'm thiniking of something similar to the 'Save profile' in the chrome's performance Tab after profiling

Thanks,
Regards,

**Comment by mgechev** [comment]
I'll close for now. We'll disable the router view for the initial release.
