### ISSUE TITLE
Docs ref icon misleading

### ISSUE THREAD

**Issue by fmalcher** [mgechev/eap-feedback#9]
The docs references for inputs/outputs is really cool!
However, I was really confused by the icon. I interpreted it as "linking things together", not "external link to a docs resource".

Suggestion: The usual "open in new" icon: https://fonts.google.com/icons?selected=Material%20Icons%3Aopen_in_new

![Screenshot 2021-04-26 at 20 50 27](https://user-images.githubusercontent.com/1683147/116136009-16c0a900-a6d2-11eb-892c-c5fd05ea6c64.png)

**Comment by mgechev** [comment]
Thanks for the feedback! We'll update today.

**Comment by mgechev** [comment]
@twerske, could you have a look?
